---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/Users/i342116/MyRepo/bookstore-products/bookstore/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
